module.exports = {
  commanMessage: {
    PASSWORD_RESET: "Password reset successfully",
    VERIFY_OTP: "Verify Otp Successfully",
    SOMETHING_WENT_WRONG: "Something went wrong",
    PASSWORD_RESET: "Password reset successful",
    VALIDATION_FAILED: "Validation Failed",
    TOKEN_MISSING: "Token is Missing, Must send Token",
    INVALID_TOKEN: "Token is Invalid",
    EMAIL_NOT_MATCHED: "Email not matched",
    PASSWORD_NOT_MATCHED: "Password not matched",
    ADMIN_LOGIN_SUCCESS: "Admin login successfully",
    COACHING_LOGIN_SUCCESS: "Coaching login successfully",
    EMAIL_REQUIRED: "Email is required",
    INVALID_ID: "Invalid User ID",
    ALL_FIELD_REQUIRED: "All field are required",
    VALIDATION_FAILED: "Opps ! validation failed",
    EMAIL_ALREADY_EXIST: "Email already exist",
    OTP_RESEND: "Resend Your Otp",
    OTP_SEND_SUCCESSFULLY: "Otp send successfully",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    PASSWORD_NOT_UPDATED: "OOPS ! Password Not Updated !",
  },
  orderMessage: {
    ORDER_CREATED: "Order Created Successfully!",
    ORDER_NOT_CREATED: "Order not Purchased!",

    ORDER_RENEWAL: "Order Renewal Successfully!",
    ORDER_NOT_RENEWAL: "Order not Renewal!",

    ORDER_UPDATED: "Order Updated Successfully !",
    ORDER_NOT_UPDATED: "Order not Updated!",

    ORDER_DELETED: "Order Deleted Successfully!",
    ORDER_NOT_DELETED: "Order not Deleted!",

    ORDER_FETCHED: "Order Fetched Successfully!",
    ORDER_NOT_FETCHED: "Order not Fetched!",

    ORDER_NOT_FOUND: "Order not Found!",
    ORDER_ERROR: "OOPS Error with Order!",

    ORDER_CANCELLED: "Order Cancelled Successfully!",
    ORDER_NOT_CANCELLED: "Order not Cancelled!",
    ORDER_ALREADY_CANCELLED: "Order already Cancelled!",

    USER_ALL_ORDER: " User All Order Details get successfully",
  },

  couponMessage: {
    COUPON_CREATED: "Coupon Created Successfully!",
    COUPON_NOT_CREATED: "Coupon not Created!",

    COUPON_UPDATED: "Coupon Updated Successfully !",
    COUPON_NOT_UPDATED: "Coupon not Updated!",

    COUPON_DELETED: "Coupon Deleted Successfully!",
    COUPON_NOT_DELETED: "Coupon not Deleted!",

    COUPON_FETCHED: "Coupon Fetched Successfully!",
    COUPON_NOT_FETCHED: "Coupon not Fetched!",

    COUPON_NOT_FOUND: "Coupon not Found!",
    COUPON_VERIFIED: "Coupon Applied!",

    COUPON_ERROR: "Oops Error with Coupon !",
    COUPON_EXISTS: "Oops Coupon Code is already exsts !",
  },

  adminMessage: {
    OTP_INVALID: "Your OTP id Invalid",
    ADMIN_CREATED: "Admin Register Successfully!",
    ADMIN_NOT_CREATED: "Admin Not Created",
    EMAIL_AND_PASSWORD_NOT_MATCH: "Email and password is not match",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
    ADMIN_NOT_FOUND: "Admin not found",
    ADMIN_DELETE: "Admin delete",
    ADMIN_NOT_FETCHED: "Admin not fetched !",
    ADMIN_FETCHED: "Admin fetched !",

    ADMIN_NOT_UPDATED: "Admin not updated !",
    ADMIN_UPDATED: "Admin updated !",
  },

  userMessage: {
    USER_LOGIN_SUCCESS: "User login successfully",
    OTP_INVALID: "Your OTP id Invalid",
    USER_CREATED: "User Register Successfully!",
    USER_NOT_CREATED: "User Not Created",
    EMAIL_AND_PASSWORD_NOT_MATCH: "Email and password is not match",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
    USER_ALL_COURSES: "All Course get sucessfully!",
    USER_NOT_FOUND: "User not found",
    USER_DELETE: "User delete",
    USER_NOT_FETCHED: "User not fetched !",
    USER_FETCHED: "User fetched !",

    USER_NOT_UPDATED: "User not updated !",
    USER_UPDATED: "User updated !",
  },

  categoryMessage: {
    CATEGORY_CREATED: "Category Created Successfully!",
    CATEGORY_ALREADY_EXIST: "Category Already Exists!",
    CATEGORY_NOT_CREATED: "Category not Created!",
    CATEGORY_UPDATED: "Category Updated Successfully !",
    CATEGORY_NOT_UPDATED: "Category not Updated!",
    CATEGORY_DELETED: "Category Deleted Successfully!",
    CATEGORY_NOT_DELETED: "Category not Deleted!",
    CATEGORY_FETCHED: "Category Fetched Successfully!",
    CATEGORY_NOT_FETCHED: "Category not Fetched!",
    CATEGORY_NOT_FOUND: "Category not Found!",
    CATEGORY_ERROR: "OOPS Error with Category!",
    CATEGORY_GET_SUCCESSFULLY: "Category get successfully",
    ALL_CATEGORY_GET_SUCCESSFULLY: "All Category get successfully",
  },

  courseMessage: {
    COURSE_ALREADY_EXIST: "Course Already Exists!",
    COURSE_CREATED: "Course Created Successfully!",
    COURSE_NOT_CREATED: "Course not Created!",
    COURSE_UPDATED: "Course Updated Successfully !",
    COURSE_NOT_UPDATED: "Course not Updated!",
    COURSE_DELETED: "Course Deleted Successfully!",
    COURSE_NOT_DELETED: "Course not Deleted!",
    COURSE_FETCHED: "Course Fetched Successfully!",
    COURSE_NOT_FETCHED: "Course not Fetched!",
    COURSE_NOT_FOUND: "Course not Found!",
    COURSE_ERROR: "OOPS Error with Course!",
    COURSE_GET_SUCCESSFULLY: "Course get successfully",
    ALL_COURSE_GET_SUCCESSFULLY: "All Course get successfully",
  },

  courseTopicMessage: {
    COURSE_TOPICS_ALREADY_EXIST: "CourseTopic Already Exists!",
    COURSE_TOPICS_CREATED: "Course Topic Created Successfully!",
    COURSE_TOPICS_NOT_CREATED: "CourseTopic not Created!",
    COURSE_TOPICS_UPDATED: "CourseTopic Updated Successfully !",
    COURSE_TOPICS_NOT_UPDATED: "CourseTopic not Updated!",
    COURSE_TOPICS_DELETED: "CourseTopic Deleted Successfully!",
    COURSE_TOPICS_NOT_DELETED: "CourseTopic not Deleted!",
    COURSE_TOPICS_FETCHED: "CourseTopic Fetched Successfully!",
    COURSE_TOPICS_NOT_FETCHED: "CourseTopic not Fetched!",
    COURSE_TOPICS_NOT_FOUND: "CourseTopic not Found!",
    COURSE_TOPICS_ERROR: "OOPS Error with CourseTopic!",
    COURSE_TOPICS_GET_SUCCESSFULLY: "CourseTopic get successfully",
    ALL_COURSE_TOPICS_GET_SUCCESSFULLY: "All CourseTopic get successfully",
  },

  courseContentMessage: {
    COURSE_CONTENT_ALREADY_EXIST: "Course Already Exists!",
    COURSE_CONTENT_CREATED: "Course Created Successfully!",
    COURSE_CONTENT_NOT_CREATED: "Course not Created!",
    COURSE_CONTENT_UPDATED: "Course Updated Successfully !",
    COURSE_CONTENT_NOT_UPDATED: "Course not Updated!",
    COURSE_CONTENT_DELETED: "Course Deleted Successfully!",
    COURSE_CONTENT_NOT_DELETED: "Course not Deleted!",
    COURSE_CONTENT_FETCHED: "Course Fetched Successfully!",
    COURSE_CONTENT_NOT_FETCHED: "Course not Fetched!",
    COURSE_CONTENT_NOT_FOUND: "Course not Found!",
    COURSE_CONTENT_ERROR: "OOPS Error with Course!",
    COURSE_CONTENT_GET_SUCCESSFULLY: "Course get successfully",
    ALL_COURSE_CONTENT_GET_SUCCESSFULLY: "All Course get successfully",
  },
};
