module.exports = {
  commanMessage: {
    PASSWORD_RESET: "Password reset successfully",
    VERIFY_OTP: "Verify Otp Successfully",
    SOMETHING_WENT_WRONG: "Something went wrong",
    PASSWORD_RESET: "Password reset successful",
    VALIDATION_FAILED: "Validation Failed",
    TOKEN_MISSING: "Token is Missing, Must send Token",
    INVALID_TOKEN: "Token is Invalid",
    EMAIL_NOT_MATCHED: "Email not matched",
    PASSWORD_NOT_MATCHED: "Password not matched",
    ADMIN_LOGIN_SUCCESS: "Admin login successfully",
    COACHING_LOGIN_SUCCESS: "Coaching login successfully",
    EMAIL_REQUIRED: "Email is required",
    INVALID_ID: "Invalid User ID",
    ALL_FIELD_REQUIRED: "All field are required",
    VALIDATION_FAILED: "Opps ! validation failed",
    EMAIL_ALREADY_EXIST: "Email already exist",
    OTP_RESEND: "Resend Your Otp",
    OTP_SEND_SUCCESSFULLY: "Otp send successfully",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    PASSWORD_NOT_UPDATED: "OOPS ! Password Not Updated !",
  },
  couponMessage: {
    COUPON_CREATED: "Coupon Created Successfully!",
    COUPON_NOT_CREATED: "Coupon not Created!",

    COUPON_UPDATED: "Coupon Updated Successfully !",
    COUPON_NOT_UPDATED: "Coupon not Updated!",

    COUPON_DELETED: "Coupon Deleted Successfully!",
    COUPON_NOT_DELETED: "Coupon not Deleted!",

    COUPON_FETCHED: "Coupon Fetched Successfully!",
    COUPON_NOT_FETCHED: "Coupon not Fetched!",

    COUPON_NOT_FOUND: "Coupon not Found!",
    COUPON_VERIFIED: "Coupon Applied!",

    COUPON_ERROR: "Oops Error with Coupon !",
    COUPON_EXISTS: "Oops Coupon Code is already exsts !",
  },
  customerMessage: {
    CUSTOMER_CREATED: "Customer Register Successfully! Need to verify Account",
    CUSTOMER_NOT_CREATED: "Customer Register Successfully!",

    CUSTOMER_NOT_FETCHED: "Customer not Fetched!",
    CUSTOMER_FETCHED: "Customer Fetched Successfully!",

    PROFILE_NOT_FETCHED: "Profile not Fetched!",
    PROFILE_FETCHED: "Profile Fetched Successfully!",

    ACCOUNT_VERIFIED: "Account Verify Successfully!",
    ACCOUNT_NOT_VERIFIED: "Account Not Verify!",

    CUSTOMER_NOT_DELETED: "Customer not Deleted",
    CUSTOMER_DELETED: "Customer Deleted!",
    ADDRESS_NOT_DELETE: "Address not Delete!",
    ADDRESS_NOT_UPDATED: "Address not Updated!",
    ADDRESS_NOT_FOUND: "Address not Found!",
    ADDRESS_ADDED: "Address Successfully Added!",
    ADDRESS_NOT_ADDED: "Address Not Added!",
    ADDRESS_FETCHED: "Address Fetched!",
    ADDRESS_UPDATED: "Address Successfully Updated!",
    ADDRESS_DELETED: "Address Successfully Deleted!",
    CUSTOMER_FETCHED: "Customer Profile Fetched Successfully!",
    CUSTOMER_NOT_FOUND: "Customer Not Found!",
    PROFILE_NOT_UPDATED: "Profile Not Updated!",
    PROFILE_UPDATED: "Profile Updated Successfully!",

    CUSTOMER_NOT_UPDATED: "Customer Not Updated!",
    CUSTOMER_UPDATED: "Customer Updated Successfully!",

    CUSTOMER_VERIFICATION_FAILED: "Account Verification Failed!",
    CUSTOMER_VERIFIED: "Account Verified!",
    OTP_SEND: "OTP Send to Your Email!",
    TRANSACTION_ADDED: "Transaction Added Successfully!",
    TRANSACTION_NOT_ADDED: "Transaction not Added!",
    ACCOUNT_VALIDATED: "Your Account is Validated!",
    PASSWORD_CREATED: "New Password is Created!",
    PASSWORD_NOT_CREATED: "Password Not Created!",
  },

  adminMessage: {
    OTP_INVALID: "Your OTP id Invalid",
    ADMIN_CREATED: "Admin Register Successfully!",
    ADMIN_NOT_CREATED: "Admin Not Created",
    EMAIL_AND_PASSWORD_NOT_MATCH: "Email and password is not match",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
    ADMIN_NOT_FOUND: "Admin not found",
    ADMIN_DELETE: "Admin delete",
    ADMIN_NOT_FETCHED: "Admin not fetched !",
    ADMIN_FETCHED: "Admin fetched !",

    ADMIN_NOT_UPDATED: "Admin not updated !",
    ADMIN_UPDATED: "Admin updated !",
  },

  userMessage: {
    USER_LOGIN_SUCCESS: "User login successfully",
    OTP_INVALID: "Your OTP id Invalid",
    USER_CREATED: "User Register Successfully!",
    USER_NOT_CREATED: "User Not Created",
    EMAIL_AND_PASSWORD_NOT_MATCH: "Email and password is not match",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",

    USER_NOT_FOUND: "User not found",
    USER_DELETE: "User delete",
    USER_NOT_FETCHED: "User not fetched !",
    USER_FETCHED: "User fetched !",

    USER_NOT_UPDATED: "User not updated !",
    USER_UPDATED: "User updated !",
  },

  categoryMessage: {
    CATEGORY_CREATED: "Category Created Successfully!",
    CATEGORY_ALREADY_EXIST: "Category Already Exists!",
    CATEGORY_NOT_CREATED: "Category not Created!",
    CATEGORY_UPDATED: "Category Updated Successfully !",
    CATEGORY_NOT_UPDATED: "Category not Updated!",
    CATEGORY_DELETED: "Category Deleted Successfully!",
    CATEGORY_NOT_DELETED: "Category not Deleted!",
    CATEGORY_FETCHED: "Category Fetched Successfully!",
    CATEGORY_NOT_FETCHED: "Category not Fetched!",
    CATEGORY_NOT_FOUND: "Category not Found!",
    CATEGORY_ERROR: "OOPS Error with Category!",
    CATEGORY_GET_SUCCESSFULLY: "Category get successfully",
    ALL_CATEGORY_GET_SUCCESSFULLY: "All Category get successfully",
  },

  courseMessage: {
    COURSE_ALREADY_EXIST: "Course Already Exists!",
    COURSE_CREATED: "Course Created Successfully!",
    COURSE_NOT_CREATED: "Course not Created!",
    COURSE_UPDATED: "Course Updated Successfully !",
    COURSE_NOT_UPDATED: "Course not Updated!",
    COURSE_DELETED: "Course Deleted Successfully!",
    COURSE_NOT_DELETED: "Course not Deleted!",
    COURSE_FETCHED: "Course Fetched Successfully!",
    COURSE_NOT_FETCHED: "Course not Fetched!",
    COURSE_NOT_FOUND: "Course not Found!",
    COURSE_ERROR: "OOPS Error with Course!",
    COURSE_GET_SUCCESSFULLY: "Course get successfully",
    ALL_COURSE_GET_SUCCESSFULLY: "All Course get successfully",
  },

  courseContentMessage: {
    COURSE_CONTENT_ALREADY_EXIST: "Course Already Exists!",
    COURSE_CONTENT_CREATED: "Course Created Successfully!",
    COURSE_CONTENT_NOT_CREATED: "Course not Created!",
    COURSE_CONTENT_UPDATED: "Course Updated Successfully !",
    COURSE_CONTENT_NOT_UPDATED: "Course not Updated!",
    COURSE_CONTENT_DELETED: "Course Deleted Successfully!",
    COURSE_CONTENT_NOT_DELETED: "Course not Deleted!",
    COURSE_CONTENT_FETCHED: "Course Fetched Successfully!",
    COURSE_CONTENT_NOT_FETCHED: "Course not Fetched!",
    COURSE_CONTENT_NOT_FOUND: "Course not Found!",
    COURSE_CONTENT_ERROR: "OOPS Error with Course!",
    COURSE_CONTENT_GET_SUCCESSFULLY: "Course get successfully",
    ALL_COURSE_CONTENT_GET_SUCCESSFULLY: "All Course get successfully",
  },

  subjectMessage: {
    SUBJECT_CREATED: "Subject Created Successfully !",
    SUBJECT_DELETED: "Subject Deleted Successfully !",
    SUBJECT_EXIST: "Subject already exist",
    SUBJECT_NOT_FOUND: "Subject not found",
    SUBJECT_UPDATED_SUCCESSFULLY: "Subject Updated successfully",
    SUBJECT_GET_SUCCESSFULLY: " Subject get successfully",
    ALL_SUBJECT_GET_SUCCESSFULLY: "All Subject get successfully",
  },
  batchMessage: {
    BATCH_CREATED: "Batch Created Successfully !",
    BATCH_DELETED: "Batch Deleted Successfully !",
    BATCH_EXIST: "Batch already exist",
    BATCH_NOT_FOUND: "Batch not found",
    BATCH_UPDATED_SUCCESSFULLY: "Batch Updated successfully",
    BATCH_GET_SUCCESSFULLY: "Batch get successfully",
    ALL_BATCH_GET_SUCCESSFULLY: "All Batch get successfully",
  },
  studentMessage: {
    STUDENT_CREATED: "Student Created Successfully !",
    STUDENT_DELETED: "Student Deleted Successfully !",
    STUDENT_EXIST: "Student already exist",
    STUDENT_NOT_FOUND: "Student not found",
    STUDENT_UPDATED_SUCCESSFULLY: "Student Updated successfully",
    STUDENT_GET_SUCCESSFULLY: "Student get successfully",
    ALL_STUDENT_GET_SUCCESSFULLY: "All Student get successfully",
  },

  sessionMessage: {
    SESSION_CREATED: "Session Created Successfully !",
    SESSION_DELETED: "Session Deleted Successfully !",
    SESSION_EXIST: "Session already exist",
    SESSION_NOT_FOUND: "Session not found",
    SESSION_UPDATED_SUCCESSFULLY: "Session Updated successfully",
    SESSION_GET_SUCCESSFULLY: "Session get successfully",
    ALL_SESSION_GET_SUCCESSFULLY: "All Session get successfully",
  },
  coachingMessage: {
    COACHING_CREATED: "Coaching Register Successfully!",
    COACHING_NOT_FOUND: "Coaching not found",
    COACHING_UPDATED: "Coaching updated !",
    COACHING_NOT_UPDATED: "Coaching not updated !",
  },

  deliveryBoyMessage: {
    DELIVERY_BOY_CREATED: "Delivery Boy Created Successfully!",
    DELIVERY_BOY_NOT_CREATED: "Delivery Boy Not Created!",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    PASSWORD_NOT_UPDATED: "OOPS ! Password Not Updated !",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
    DELIVERY_BOY_FETCHED: "Delivery Boy Fetched Successfully !",
    DELIVERY_BOY_NOT_FETCHED: "Delivery Boy Not Fetched !",
    DELIVERY_BOY_UPDATED: "Delivery Boy Updated Successfully!",
    DELIVERY_BOY_NOT_UPDATED: "Delivery Boy Not Updated!",

    PINCODE_UPDATED: "Pincode Updated Successfully!",
    PINCODE_NOT_UPDATED: "Pincode Not Updated!",
  },

  supervisorMessage: {
    SUPERVISOR_CREATED: "Supervisor Created Successfully!",
    SUPERVISOR_NOT_CREATED: "Supervisor Not Created!",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    PASSWORD_NOT_UPDATED: "OOPS ! Password Not Updated !",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
    SUPERVISOR_FETCHED: "Supervisor Fetched Successfully !",
    SUPERVISOR_NOT_FETCHED: "Supervisor Not Fetched !",
    SUPERVISOR_UPDATED: "Supervisor Updated Successfully!",
    SUPERVISOR_NOT_UPDATED: "Supervisor Not Updated!",
    SUPERVISOR_DELETED: "Supervisor Deleted Successfully!",
    SUPERVISOR_NOT_DELETED: "Supervisor Not Deleted!",
  },
  authMessage: {
    EMAIL_EXISTS: "This Email is already exists!",
    NEED_VERIFICATION: "Account exists, need verification",
    NEED_LOGIN: "Account Exists, Need Login",
    ACCOUNT_DISABLED: "Sorry Your Account is Disabled",
    ACCOUNT_NOT_VERIFIED: "Your Account is not verified, verify first",
    INVALID_EMAIL: "You entered wrong Email Id",
    OTP_FAILED: "OTP Failed",
    OTP_SUCCESS: "OTP Send Successfully !",
    INVALID_PASSWORD: "Password is Wrong!",
    LOGIN_SUCCESS: "Successfully Logedin",
    LOGIN_FAILED: "Login Failed !",
    REGISTRATION_SUCCESS: "Registration Successfully !",
    REGISTRATION_FAILED: "Registration Failed !",
    ACCOUNT_VALIDATED: "Account Validated Successfully !",
  },

  subCategoryMessage: {
    SUB_CATEGORY_CREATED: "Sub Category Created Successfully!",
    SUB_CATEGORY_ALREADY_EXIST: "Sub Category Already Exists!",
    SUB_CATEGORY_NOT_CREATED: "Sub Category not Created!",
    SUB_CATEGORY_UPDATED: "Sub Category Updated Successfully !",
    SUB_CATEGORY_NOT_UPDATED: "Sub Category not Updated!",
    SUB_CATEGORY_DELETED: "Sub Category Deleted Successfully!",
    SUB_CATEGORY_NOT_DELETED: "Sub Category not Deleted!",
    SUB_CATEGORY_FETCHED: "Sub Category Fetched Successfully!",
    SUB_CATEGORY_NOT_FETCHED: "Sub Category not Fetched!",
    SUB_CATEGORY_NOT_FOUND: "Sub Category not Found!",
    SUB_CATEGORY_ERROR: "OOPS Error with Sub Category!",
  },
  occasionMessage: {
    OCCASION_CREATED: "Occassion Created Successfully!",
    OCCASION_ALREADY_EXIST: "Occassion Already Exists!",
    OCCASION_NOT_CREATED: "Occassion not Created!",
    OCCASION_UPDATED: "Occassion Updated Successfully !",
    OCCASION_NOT_UPDATED: "Occassion not Updated!",
    OCCASION_DELETED: "Occassion Deleted Successfully!",
    OCCASION_NOT_DELETED: "Occassion not Deleted!",
    OCCASION_FETCHED: "Occassion Fetched Successfully!",
    OCCASION_NOT_FETCHED: "Occassion not Fetched!",
    OCCASION_NOT_FOUND: "Occassion not Found!",
    OCCASION_ERROR: "OOPS Error with Occassion!",
  },
  blogPostMessage: {
    BLOG_POST_CREATED: "Blog Post Created Successfully!",
    BLOG_POST_ALREADY_EXIST: "Blog Post Already Exists!",
    BLOG_POST_NOT_CREATED: "Blog Post not Created!",
    BLOG_POST_UPDATED: "Blog Post Updated Successfully !",
    BLOG_POST_NOT_UPDATED: "Blog Post not Updated!",
    BLOG_POST_DELETED: "Blog Post Deleted Successfully!",
    BLOG_POST_NOT_DELETED: "Blog Post not Deleted!",
    BLOG_POST_FETCHED: "Blog Post Fetched Successfully!",
    BLOG_POST_NOT_FETCHED: "Blog Post not Fetched!",
    BLOG_POST_NOT_FOUND: "Blog Post not Found!",
    BLOG_POST_ERROR: "OOPS Error with Blog Post!",
  },
  newsletterMessage: {
    NEWSLETTER_CREATED: "Newsletter Created Successfully!",
    NEWSLETTER_ALREADY_EXIST: "Email Already Exists!",
    NEWSLETTER_NOT_CREATED: "Newsletter not Created!",
    NEWSLETTER_UPDATED: "Newsletter Updated Successfully !",
    NEWSLETTER_NOT_UPDATED: "Newsletter not Updated!",
    NEWSLETTER_DELETED: "Newsletter Deleted Successfully!",
    NEWSLETTER_NOT_DELETED: "Newsletter not Deleted!",
    NEWSLETTER_FETCHED: "Newsletter Fetched Successfully!",
    NEWSLETTER_NOT_FETCHED: "Newsletter not Fetched!",
    NEWSLETTER_NOT_FOUND: "Newsletter not Found!",
    NEWSLETTER_ERROR: "OOPS Error with Newsletter !",
  },

  faqsMessage: {
    FAQS_CREATED: "Faqs Created Successfully!",
    FAQS_ALREADY_EXIST: "Email Already Exists!",
    FAQS_NOT_CREATED: "Faqs not Created!",
    FAQS_UPDATED: "Faqs Updated Successfully !",
    FAQS_NOT_UPDATED: "Faqs not Updated!",
    FAQS_DELETED: "Faqs Deleted Successfully!",
    FAQS_NOT_DELETED: "Faqs not Deleted!",
    FAQS_FETCHED: "Faqs Fetched Successfully!",
    FAQS_NOT_FETCHED: "Faqs not Fetched!",
    FAQS_NOT_FOUND: "Faqs not Found!",
    FAQS_ERROR: "OOPS Error with Faqs !",
  },

  mainMenuMessage: {
    MAINMENU_CREATED: "Main Menu Created Successfully!",
    MAINMENU_ALREADY_EXIST: "Main Menu Already Exists!",
    MAINMENU_NOT_CREATED: "Main Menu not Created!",
    MAINMENU_UPDATED: "Main Menu Updated Successfully !",
    MAINMENU_NOT_UPDATED: "Main Menu not Updated!",
    MAINMENU_DELETED: "Main Menu Deleted Successfully!",
    MAINMENU_NOT_DELETED: "Main Menu not Deleted!",
    MAINMENU_FETCHED: "Main Menu Fetched Successfully!",
    MAINMENU_NOT_FETCHED: "Main Menu not Fetched!",
    MAINMENU_NOT_FOUND: "Main Menu not Found!",
    MAINMENU_ERROR: "OOPS Error with Main Menu !",
  },
  inquiryMessage: {
    INQUIRY_CREATED: "Inquiry Created Successfully!",
    INQUIRY_ALREADY_EXIST: "Inquiry Already Exists!",
    INQUIRY_NOT_CREATED: "Inquiry not Created!",
    INQUIRY_UPDATED: "Inquiry Updated Successfully !",
    INQUIRY_NOT_UPDATED: "Inquiry not Updated!",
    INQUIRY_DELETED: "Inquiry Deleted Successfully!",
    INQUIRY_NOT_DELETED: "Inquiry not Deleted!",
    INQUIRY_FETCHED: "Inquiry Fetched Successfully!",
    INQUIRY_NOT_FETCHED: "Inquiry not Fetched!",
    INQUIRY_NOT_FOUND: "Inquiry not Found!",
    INQUIRY_ERROR: "OOPS Error with Inquiry !",
  },
  productMessage: {
    PRODUCT_CREATED: "Product Created Successfully!",
    PRODUCT_NOT_CREATED: "Product not Created!",
    PRODUCT_UPDATED: "Product Updated Successfully !",
    PRODUCT_NOT_UPDATED: "Product not Updated!",
    PRODUCT_DELETED: "Product Deleted Successfully!",
    PRODUCT_NOT_DELETED: "Product not Deleted!",
    PRODUCT_FETCHED: "Product Fetched Successfully!",
    PRODUCT_NOT_FETCHED: "Product not Fetched!",
    PRODUCT_NOT_FOUND: "Product not Found!",
    PRODUCT_ERROR: "OOPS Error with Product!",
  },
  deliveryDetailsMessage: {
    DELIVERY_DETAILS_CREATED: "Delivery Details Added Successfully!",
    DELIVERY_DETAILS_NOT_CREATED: "Delivery Details not Added!",

    DELIVERY_DETAILS_SKIPPED: "Delivery Details Skipped Successfully!",
    DELIVERY_DETAILS_NOT_SKIPPED: "Delivery Details not Skipped!",

    DELIVERY_DETAILS_UPDATED: "Delivery Details Updated Successfully !",
    DELIVERY_DETAILS_NOT_UPDATED: "Delivery Details not Updated!",

    DELIVERY_DETAILS_DELETED: "Delivery Details Deleted Successfully!",
    DELIVERY_DETAILS_NOT_DELETED: "Delivery Details not Deleted!",

    DELIVERY_DETAILS_FETCHED: "Delivery Details Fetched Successfully!",
    DELIVERY_DETAILS_NOT_FETCHED: "Delivery Details not Fetched!",

    DELIVERY_DETAILS_NOT_FOUND: "Delivery Details not Found!",
    DELIVERY_DETAILS_ERROR: "OOPS Error with Delivery Details!",

    DELIVERY_DETAILS_CANCELLED: "Delivery Details Cancelled Successfully!",
    DELIVERY_DETAILS_NOT_CANCELLED: "Delivery Details not Cancelled!",
  },

  subscriptionMessage: {
    SUBSCRIPTION_CREATED: "Subscription Purchased Successfully!",
    SUBSCRIPTION_NOT_CREATED: "Subscription not Purchased!",

    SUBSCRIPTION_RENEWAL: "Subscription Renewal Successfully!",
    SUBSCRIPTION_NOT_RENEWAL: "Subscription not Renewal!",

    SUBSCRIPTION_UPDATED: "Subscription Updated Successfully !",
    SUBSCRIPTION_NOT_UPDATED: "Subscription not Updated!",

    SUBSCRIPTION_DELETED: "Subscription Deleted Successfully!",
    SUBSCRIPTION_NOT_DELETED: "Subscription not Deleted!",

    SUBSCRIPTION_FETCHED: "Subscription Fetched Successfully!",
    SUBSCRIPTION_NOT_FETCHED: "Subscription not Fetched!",

    SUBSCRIPTION_NOT_FOUND: "Subscription not Found!",
    SUBSCRIPTION_ERROR: "OOPS Error with Subscription!",

    SUBSCRIPTION_CANCELLED: "Subscription Cancelled Successfully!",
    SUBSCRIPTION_NOT_CANCELLED: "Subscription not Cancelled!",
  },
  subscriptionHistoryMessage: {
    SUBSCRIPTION_HISTORY_CREATED: "Subscription history created!",
    SUBSCRIPTION_HISTORY_NOT_CREATED:
      "Oops ! Subscription history not created!",

    SUBSCRIPTION_HISTORY_DELETED: "Subscription Deleted Successfully!",
    SUBSCRIPTION_HISTORY_NOT_DELETED: "Subscription not Deleted!",

    SUBSCRIPTION_HISTORY_FETCHED: "Subscription Fetched Successfully!",
    SUBSCRIPTION_HISTORY_NOT_FETCHED: "Subscription not Fetched!",

    SUBSCRIPTION_HISTORY_NOT_FOUND: "Subscription not Found!",
    SUBSCRIPTION_HISTORY_ERROR: "OOPS Error with Subscription!",
  },

  orderMessage: {
    ORDER_CREATED: "Order Created Successfully!",
    ORDER_NOT_CREATED: "Order not Purchased!",

    ORDER_RENEWAL: "Order Renewal Successfully!",
    ORDER_NOT_RENEWAL: "Order not Renewal!",

    ORDER_UPDATED: "Order Updated Successfully !",
    ORDER_NOT_UPDATED: "Order not Updated!",

    ORDER_DELETED: "Order Deleted Successfully!",
    ORDER_NOT_DELETED: "Order not Deleted!",

    ORDER_FETCHED: "Order Fetched Successfully!",
    ORDER_NOT_FETCHED: "Order not Fetched!",

    ORDER_NOT_FOUND: "Order not Found!",
    ORDER_ERROR: "OOPS Error with Order!",

    ORDER_CANCELLED: "Order Cancelled Successfully!",
    ORDER_NOT_CANCELLED: "Order not Cancelled!",
    ORDER_ALREADY_CANCELLED: "Order already Cancelled!",
  },

  orderHistoryMessage: {
    ORDER_HISTORY_CREATED: "Order history created!",
    ORDER_HISTORY_NOT_CREATED: "Oops ! Order history not created!",

    ORDER_HISTORY_DELETED: "Order Deleted Successfully!",
    ORDER_HISTORY_NOT_DELETED: "Order not Deleted!",

    ORDER_HISTORY_FETCHED: "Order Fetched Successfully!",
    ORDER_HISTORY_NOT_FETCHED: "Order not Fetched!",

    ORDER_HISTORY_NOT_FOUND: "Order not Found!",
    ORDER_HISTORY_ERROR: "OOPS Error with Order!",
  },

  reportMessage: {
    TOP_CUSTOMER_FETCHED: "Top customers fetched successfully!",
    TOP_CUSTOMER_NOT_FETCHED: "Top customers not fetched!",

    TOP_PRODUCTS_FETCHED: "Top products fetched successfully!",
    TOP_PRODUCTS_NOT_FETCHED: "Top products not fetched!",
  },

  bucketMessage: {
    BUCKET_CREATED: "Bucket Created Successfully!",
    BUCKET_NOT_CREATED: "Bucket not Created!",
    BUCKET_UPDATED: "Bucket Updated Successfully !",
    BUCKET_NOT_UPDATED: "Bucket not Updated!",
    BUCKET_DELETED: "Bucket Deleted Successfully!",
    BUCKET_NOT_DELETED: "Bucket not Deleted!",
    BUCKET_FETCHED: "Bucket Fetched Successfully!",
    BUCKET_NOT_FETCHED: "Bucket not Fetched!",
    BUCKET_NOT_FOUND: "Bucket not Found!",
    BUCKET_ERROR: "OOPS Error with Bucket!",
  },
  dealsMessage: {
    DEALS_CREATED: "Deals Created Successfully!",
    DEALS_NOT_CREATED: "Deals not Created!",
    DEALS_UPDATED: "Deals Updated Successfully !",
    DEALS_NOT_UPDATED: "Deals not Updated!",
    DEALS_DELETED: "Deals Deleted Successfully!",
    DEALS_NOT_DELETED: "Deals not Deleted!",
    DEALS_FETCHED: "Deals Fetched Successfully!",
    DEALS_NOT_FETCHED: "Deals not Fetched!",
    DEALS_NOT_FOUND: "Deals not Found!",
    DEALS_ERROR: "OOPS Error with Deals!",
  },

  wishlistMessage: {
    WISHLIST_CREATED: "Product Added to Wishlist !",
    PRODUCT_EXISTS: "Product Already exists in Wishlist !",
    WISHLIST_NOT_CREATED: "Wishlist not Created!",
    WISHLIST_UPDATED: "Wishlist Updated Successfully !",
    WISHLIST_NOT_UPDATED: "Wishlist not Updated!",
    WISHLIST_DELETED: "Product Deleted from Wishlist !",
    WISHLIST_NOT_DELETED: "Wishlist not Deleted!",
    WISHLIST_FETCHED: "Wishlist Fetched Successfully!",
    WISHLIST_NOT_FETCHED: "Wishlist not Fetched!",
    WISHLIST_NOT_FOUND: "Wishlist not Found!",
    WISHLIST_ERROR: "OOPS Error with Wishlist!",
  },
  couponMessage: {
    COUPON_CREATED: "Coupon Created Successfully!",
    COUPON_NOT_CREATED: "Coupon not Created!",

    COUPON_UPDATED: "Coupon Updated Successfully !",
    COUPON_NOT_UPDATED: "Coupon not Updated!",

    COUPON_DELETED: "Coupon Deleted Successfully!",
    COUPON_NOT_DELETED: "Coupon not Deleted!",

    COUPON_FETCHED: "Coupon Fetched Successfully!",
    COUPON_NOT_FETCHED: "Coupon not Fetched!",

    COUPON_NOT_FOUND: "Coupon not Found!",
    COUPON_INVALID: "You entered invalid coupon!",
    COUPON_VERIFIED: "Coupon Applied!",

    COUPON_ERROR: "Oops Error with Coupon !",
    COUPON_EXISTS: "Oops Coupon Code is already exsts !",
  },
  flavourMessage: {
    FLAVOUR_CREATED: "flavour Created Successfully !",
    FLAVOUR_NOT_CREATED: "flavour not Created!",
    FLAVOUR_UPDATED: "flavour Updated Successfully !",
    FLAVOUR_NOT_UPDATED: "flavour not Updated!",
    FLAVOUR_DELETED: "flavour Deleted Successfully!",
    FLAVOUR_NOT_DELETED: "flavour not Deleted!",
    FLAVOUR_FETCHED: "flavour Fetched Successfully!",
    FLAVOUR_NOT_FETCHED: "flavour not Fetched!",
    FLAVOUR_NOT_FOUND: "flavour not Found!",
    FLAVOUR_ERROR: "OOPS Error with flavour!",
  },
  pincodeMessage: {
    PINCODE_CREATED: "Pincode Created Successfully!",
    PINCODE_ALREADY_EXIST: "Pincode Already Exist!",
    PINCODE_NOT_CREATED: "Pincode not Created!",
    PINCODE_UPDATED: "Pincode Updated Successfully !",
    PINCODE_NOT_UPDATED: "Pincode not Updated!",
    PINCODE_DELETED: "Pincode Deleted Successfully!",
    PINCODE_NOT_DELETED: "Pincode not Deleted!",
    PINCODE_FETCHED: "Pincode Fetched Successfully!",
    PINCODE_NOT_FETCHED: "Pincode not Fetched!",
    PINCODE_NOT_FOUND: "Pincode not Found!",
    PINCODE_ERROR: "OOPS Error with Pincode!",
    PINCODE_NOT_FOR_DELIVERY:
      "Oops ! Delivery is not available for this Pincode!",
  },
  areaMessage: {
    AREA_CREATED: "Area Created Successfully!",
    AREA_ALREADY_EXIST: "Area Already Exist!",
    AREA_NOT_CREATED: "Area not Created!",
    AREA_UPDATED: "Area Updated Successfully !",
    AREA_NOT_UPDATED: "Area not Updated!",
    AREA_DELETED: "Area Deleted Successfully!",
    AREA_NOT_DELETED: "Area not Deleted!",
    AREA_FETCHED: "Area Fetched Successfully!",
    AREA_NOT_FETCHED: "Area not Fetched!",
    AREA_NOT_FOUND: "Area not Found!",
    AREA_ERROR: "OOPS Error with Area!",
    AREA_NOT_FOR_DELIVERY: "Oops ! Delivery is not available for this Area!",
  },
  reviewMessage: {
    REVIEW_CREATED: "Review Created Successfully!",
    REVIEW_NOT_CREATED: "Review not Created!",
    REVIEW_UPDATED: "Review Updated Successfully !",
    REVIEW_NOT_UPDATED: "Review not Updated!",
    REVIEW_DELETED: "Review Deleted Successfully!",
    REVIEW_NOT_DELETED: "Review not Deleted!",
    REVIEW_FETCHED: "Review Fetched Successfully!",
    REVIEW_NOT_FETCHED: "Review not Fetched!",
    REVIEW_NOT_FOUND: "Review not Found!",
    REVIEW_ERROR: "OOPS Error with Review!",
  },
  shapeMessage: {
    SHAPE_CREATED: "Shape Created Successfully!",
    SHAPE_NOT_CREATED: "Shape not Created!",
    SHAPE_UPDATED: "Shape Updated Successfully !",
    SHAPE_NOT_UPDATED: "Shape not Updated!",
    SHAPE_DELETED: "Shape Deleted Successfully!",
    SHAPE_NOT_DELETED: "Shape not Deleted!",
    SHAPE_FETCHED: "Shape Fetched Successfully!",
    SHAPE_NOT_FETCHED: "Shape not Fetched!",
    SHAPE_NOT_FOUND: "Shape not Found!",
    SHAPE_ERROR: "OOPS Error with Shape!",
  },
  typeMessage: {
    TYPE_CREATED: "Cake Type Created Successfully!",
    TYPE_NOT_CREATED: "Cake Type not Created!",
    TYPE_UPDATED: "Cake Type Updated Successfully !",
    TYPE_NOT_UPDATED: "Cake Type not Updated!",
    TYPE_DELETED: "Cake Type Deleted Successfully!",
    TYPE_NOT_DELETED: "Cake Type not Deleted!",
    TYPE_FETCHED: "Cake Type Fetched Successfully!",
    TYPE_NOT_FETCHED: "Cake Type not Fetched!",
    TYPE_NOT_FOUND: "Cake Type not Found!",
    TYPE_ERROR: "OOPS Error with Cake Type!",
  },

  colorMessage: {
    COLOR_CREATED: "Color Created Successfully!",
    COLOR_NOT_CREATED: "Color not Created!",
    COLOR_ALREADY_EXIST: "Colour Already Exists!",
    COLOR_UPDATED: "Color Updated Successfully !",
    COLOR_NOT_UPDATED: "Color not Updated!",
    COLOR_DELETED: "Color Deleted Successfully!",
    COLOR_NOT_DELETED: "Color not Deleted!",
    COLOR_FETCHED: "Color Fetched Successfully!",
    COLOR_NOT_FETCHED: "Color not Fetched!",
    COLOR_NOT_FOUND: "Color not Found!",
    COLOR_ERROR: "OOPS Error with Color!",
  },

  billMessage: {
    BILL_CREATED: "Bill Created Successfully!",
    BILL_NOT_CREATED: "Bill not Created!",
    BILL_ALREADY_EXIST: "Colour Already Exists!",
    BILL_UPDATED: "Bill Updated Successfully !",
    BILL_NOT_UPDATED: "Bill not Updated!",
    BILL_DELETED: "Bill Deleted Successfully!",
    BILL_NOT_DELETED: "Bill not Deleted!",
    BILL_FETCHED: "Bill Fetched Successfully!",
    BILL_NOT_FETCHED: "Bill not Fetched!",
    BILL_NOT_FOUND: "Bill not Found!",
    BILL_ERROR: "OOPS Error with Bill!",
  },

  sizeMessage: {
    SIZE_CREATED: "Size Created Successfully!",
    SIZE_NOT_CREATED: "Size not Created!",
    SIZE_ALREADY_EXIST: "Colour Already Exists!",
    SIZE_UPDATED: "Size Updated Successfully !",
    SIZE_NOT_UPDATED: "Size not Updated!",
    SIZE_DELETED: "Size Deleted Successfully!",
    SIZE_NOT_DELETED: "Size not Deleted!",
    SIZE_FETCHED: "Size Fetched Successfully!",
    SIZE_NOT_FETCHED: "Size not Fetched!",
    SIZE_NOT_FOUND: "Size not Found!",
    SIZE_ERROR: "OOPS Error with Size!",
  },
  productSizeMessage: {
    SIZE_CREATED: "Size Created Successfully!",
    SIZE_NOT_CREATED: "Size not Created!",
    SIZE_ALREADY_EXIST: "Size Already Exists!",
    SIZE_UPDATED: "Size Updated Successfully !",
    SIZE_NOT_UPDATED: "Size not Updated!",
    SIZE_DELETED: "Size Deleted Successfully!",
    SIZE_NOT_DELETED: "Size not Deleted!",
    SIZE_FETCHED: "Size Fetched Successfully!",
    SIZE_NOT_FETCHED: "Size not Fetched!",
    SIZE_NOT_FOUND: "Size not Found!",
    SIZE_ERROR: "OOPS Error with Size!",
  },
  productColorMessage: {
    COLOR_CREATED: "Color Created Successfully!",
    COLOR_NOT_CREATED: "Color not Created!",
    COLOR_ALREADY_EXIST: "Colour Already Exists!",
    COLOR_UPDATED: "Color Updated Successfully !",
    COLOR_NOT_UPDATED: "Color not Updated!",
    COLOR_DELETED: "Color Deleted Successfully!",
    COLOR_NOT_DELETED: "Color not Deleted!",
    COLOR_FETCHED: "Color Fetched Successfully!",
    COLOR_NOT_FETCHED: "Color not Fetched!",
    COLOR_NOT_FOUND: "Color not Found!",
    COLOR_ERROR: "OOPS Error with Color!",
  },
  settingMessage: {
    SETTING_UPDATED: "Setting Updated Successfully !",
    SETTING_NOT_UPDATED: "Setting not Updated!",
    SETTING_FETCHED: "Setting Fetched Successfully!",
    SETTING_NOT_FETCHED: "Setting not Fetched!",
    SETTING_NOT_FOUND: "Setting not Found!",
    SETTING_ERROR: "OOPS Error with Setting!",
  },
  shippingMethodMessage: {
    SHIPPING_METHOD_CREATED: "Shipping Method Created Successfully!",
    SHIPPING_METHOD_NOT_CREATED: "Shipping Method not Created!",
    SHIPPING_METHOD_UPDATED: "Shipping Method Updated Successfully !",
    SHIPPING_METHOD_NOT_UPDATED: "Shipping Method not Updated!",
    SHIPPING_METHOD_DELETED: "Shipping Method Deleted Successfully!",
    SHIPPING_METHOD_NOT_DELETED: "Shipping Method not Deleted!",
    SHIPPING_METHOD_FETCHED: "Shipping Method Fetched Successfully!",
    SHIPPING_METHOD_NOT_FETCHED: "Shipping Method not Fetched!",
    SHIPPING_METHOD_NOT_FOUND: "Shipping Method not Found!",
    SHIPPING_METHOD_ERROR: "OOPS Error with Shipping Method!",
  },
  testimonialMessage: {
    TESTIMONIAL_CREATED: "Testimonial Created Successfully!",
    TESTIMONIAL_ALREADY_EXIST: "Testimonial Already Exists!",
    TESTIMONIAL_NOT_CREATED: "Testimonial not Created!",
    TESTIMONIAL_UPDATED: "Testimonial Updated Successfully !",
    TESTIMONIAL_NOT_UPDATED: "Testimonial not Updated!",
    TESTIMONIAL_DELETED: "Testimonial Deleted Successfully!",
    TESTIMONIAL_NOT_DELETED: "Testimonial not Deleted!",
    TESTIMONIAL_FETCHED: "Testimonial Fetched Successfully!",
    TESTIMONIAL_NOT_FETCHED: "Testimonial not Fetched!",
    TESTIMONIAL_NOT_FOUND: "Testimonial not Found!",
    TESTIMONIAL_ERROR: "OOPS Error with Testimonial !",
  },
  databaseMessage: {
    INVALID_OBJECTID: "Object ID is Invalid",
  },

  privacyPolicyMessage: {
    PRIVACY_POLICY_CREATED: "Privacy Pilicy Created Successfully!",
    PRIVACY_POLICY_NOT_CREATED: "Privacy Pilicy not Created!",
    PRIVACY_POLICY_UPDATED: "Privacy Pilicy Updated Successfully !",
    PRIVACY_POLICY_NOT_UPDATED: "Privacy Pilicy not Updated!",
    PRIVACY_POLICY_FETCHED: "Privacy Pilicy Fetched Successfully!",
    PRIVACY_POLICY_NOT_FETCHED: "Privacy Pilicy not Fetched!",
    PRIVACY_POLICY_ERROR: "OOPS Error with Privacy Pilicy !",
  },

  termsConditionsMessage: {
    TERMS_CONDITIONS_CREATED: "Terms & Conditions Created Successfully!",
    TERMS_CONDITIONS_NOT_CREATED: "Terms & Conditions not Created!",
    TERMS_CONDITIONS_UPDATED: "Terms & Conditions Updated Successfully !",
    TERMS_CONDITIONS_NOT_UPDATED: "Terms & Conditions not Updated!",
    TERMS_CONDITIONS_FETCHED: "Terms & Conditions Fetched Successfully!",
    TERMS_CONDITIONS_NOT_FETCHED: "Terms & Conditions not Fetched!",
    TERMS_CONDITIONS_ERROR: "OOPS Error with Terms & Conditions !",
  },
  contactUsMessage: {
    CONTACT_US_CREATED: "Contact Us Created Successfully!",
    CONTACT_US_NOT_CREATED: "Contact Us not Created!",
    CONTACT_US_UPDATED: "Contact Us Updated Successfully !",
    CONTACT_US_NOT_UPDATED: "Contact Us not Updated!",
    CONTACT_US_FETCHED: "Contact Us Fetched Successfully!",
    CONTACT_US_NOT_FETCHED: "Contact Us not Fetched!",
    CONTACT_US_ERROR: "OOPS Error with Contact Us !",
  },
  aboutUsMessage: {
    ABOUT_US_CREATED: "About Us Created Successfully!",
    ABOUT_US_NOT_CREATED: "About Us not Created!",
    ABOUT_US_UPDATED: "About Us Updated Successfully !",
    ABOUT_US_NOT_UPDATED: "About Us not Updated!",
    ABOUT_US_FETCHED: "About Us Fetched Successfully!",
    ABOUT_US_NOT_FETCHED: "About Us not Fetched!",
    ABOUT_US_ERROR: "OOPS Error with About Us !",
  },
  reviewsMessage: {
    REVIEWS_CREATED: "Reviews Created Successfully",
    REVIEWS_NOT_CREATED: "Reviews Not Created ",
    REVIEWS_FETCHED: "Reviews Fetched Successfully",
    REVIEWS_NOT_FETCHED: "Reviews Not Fetched",
    REVIEWS_UPDATED: "Reviews Updated Successfully",
    REVIEWS_NOT_UPDATED: "Reviews Not Updated",
    REVIEWS_DELETED: "Reviews Deleted Successfully",
    REVIEWS_NOT_DELETED: "Reviews Not Deleted",
    REVIEWS_NOT_FOUND: "Reviews Not Found",
    REVIEWS_ALREADY_EXISTS: "Reviews Already Exists",
    REVIEWS_NOT_EXISTS: "Reviews Not Exists",
  },
  wishlistMessage: {
    WISHLIST_CREATED: "Product added to wishlist",
    WISHLIST_NOT_CREATED: "Wishlist Not Created",
    WISHLIST_FETCHED: "Wishlist Fetched Successfully",
    WISHLIST_NOT_FETCHED: "Wishlist Not Fetched",
    WISHLIST_UPDATED: "Wishlist Updated Successfully",
    WISHLIST_NOT_UPDATED: "Wishlist Not Updated",
    WISHLIST_DELETED: "Product deleted from wishlist",
    WISHLIST_NOT_DELETED: "Wishlist Not Deleted",
    WISHLIST_NOT_FOUND: "Wishlist Not Found",
    WISHLIST_ALREADY_EXISTS: "Product already exists",
    WISHLIST_NOT_EXISTS: "Wishlist Not Exists",
  },
};
